### ISSUE TITLE
Add support for `Token Ownership Transfer` transaction

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signumjs#42]
**Describe the solution you'd like**
As the new incoming Signum Node Version `3.6.1` will include a new transaction type which is called `Token Ownership Transfer` adjustments are necessary.

Is necessary to add support for `Token Ownership Transfer` transactions
The new function to be added can be called ``transferAssetOwnership`` or ``transferAssetOwner``

**Additional context**
The new function will belong to `Interface AssetApi`

- [x] Add method to API
- [x] Extend Tx Type constants
- [x] Add tx verification

**Comment by ohager** [comment]
with the upcoming tx verification we also need to add that new tx to the verification
