### ISSUE TITLE
Add more decent Documentation

### ISSUE THREAD

**Issue by ohager** [signum-network/signumjs#5]
**Is your feature request related to a problem? Please describe.**
Although having a auto-generated API documentation available it's always better to have a decent documentation, which makes onboarding (devx) much more comfortable. The better the documentation, the better the acceptance/adoption

**Describe the solution you'd like**
Add an examples folder with structured examples for most common use cases. [BurstJS Examples](https://github.com/ohager/burstjs-examples) can be a starting point, showing off how to use in vanilla js web sites, or modern apps like React, Svelte, and show how to use with NodeJS

__[UPDATE]__

Most probably, we will go with gitbook and establish a much more dev-friendly documentation

**Comment by ohager** [comment]
This will be done with gitbook.... changing title

**Comment by ohager** [comment]
wokring on docs now: https://signum-network.gitbook.io/signumjs/

**Comment by ipr0310** [comment]
Documentation has been migrated to the following platform:
https://docs.signum.network/signum/signumjs
