### ISSUE TITLE
Add support for STLDs in `setAlias` method on `DescriptorDataBuilder` class

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signumjs#57]
**Is your feature request related to a problem? Please describe.**
As the upcoming node version is bringing changes on Alias Framework, which means that STLDs are relatively new. 
the `setAlias` method will need to support the upcoming new alias format: https://github.com/signum-network/SIPs/pull/90
![image](https://user-images.githubusercontent.com/35440957/229691407-4d5fc1b8-8ac4-49e2-9643-5f55053728f4.png)

**Describe the solution you'd like**
Update the `setAlias` method in order to support STLDs

**This is the Regex statement**
`/^(\w+)(?:\.(\w+))?$/g`

**Comment by ohager** [comment]
https://github.com/signum-network/signumjs/blob/main/packages/standards/src/src44/validateSRC44.ts#L51
