### ISSUE TITLE
Add support for `keepAlive` when creating subscriptions

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signumjs#62]
**Is your feature request related to a problem? Please describe.**
As the Signum SIP-42 introduced a new property called `keepAlive` on subscriptions, SignumJS does not support setting the initial `keepAlive` value when creating subscriptions

**Describe the solution you'd like**
Add support for `keepAlive` property when creating the subscription
https://signum-network.github.io/signumjs/interfaces/core.createsubscriptionargs.html
![image](https://github.com/signum-network/signumjs/assets/35440957/8312e75f-8ece-45d5-8e18-1b24a9e052c0)

**Additional context**
If you want to learn more about the new `keepAlive` property, please visit the link of the SIP:
https://github.com/signum-network/SIPs/blob/master/SIP/sip-42.md

**Comment by frankTheTank72** [comment]
Maybe a bit to early

**Comment by ipr0310** [comment]
Will close this ticket, until keepAlive feature is fully implemented
