### ISSUE TITLE
Allow to get all custom field data in Descriptor

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signumjs#67]
**Is your feature request related to a problem? Please describe.**
In a current scenario, updating any `Signum Asset with Mutable Description`

i want to only get all custom fields of  `SRC44` `content/description`
I am limited to only get one custom field per execution
```typescript
 descriptorData.getCustomField("X-CUSTOMFIELD")
 /// https://signum-network.github.io/signumjs/classes/standards_src44.descriptordata.html#getcustomfield
```

**Describe the solution you'd like**
A method for getting all custom fields from the `SRC44` `content/description` in one execution
Example:
```typescript
const customFields= descriptorData.getCustomFields();
/// customFields is equal to {x-twitter: ipr010, x-reddit: ipr0310}
```

**Comment by ipr0310** [comment]
By the time on SignumSwap, i'll be using `Merge` method

**Comment by ohager** [comment]
you can use `DescriptorData.raw`
