### ISSUE TITLE
API Documentation page contains an invalid link

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signumjs#71]
**Describe the bug**
As the title says, if i visit https://signum-network.github.io/signumjs/ 
and I click on the `@signumjs/standards` link, it redirects me to a non existing page

**Reproduce issue**
- Visit https://signum-network.github.io/signumjs/#packages
- Click on `@signumjs/standards`

![image](https://github.com/signum-network/signumjs/assets/35440957/39332696-441d-4bc7-a8a7-a6da16318f0f)

**Comment by ohager** [comment]
done
