### ISSUE TITLE
Make improvements on `Account` interface

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signumjs#73]
The release of the node `v3.8.0` has implemented new properties on the response of the request `getAccount`
**Example of the response**
```json
{
  "balanceNQT": "6175175744000",
  "unconfirmedBalanceNQT": "6175175744000",
  "forgedBalanceNQT": "0",
  "guaranteedBalanceNQT": "6175175744000",
  "account": "2402520554221019656",
  "accountRS": "TS-QAJA-QW5Y-SWVP-4RVP4",
  "accountRSExtended": "TS-QAJA-QW5Y-SWVP-4RVP4-4U4ZCOBGZ9UPEQZQH4TSPXADMT7VHPPI53ZTWNUK9NZLXSDRNU",
  "publicKey": "c213e4144ba84af94aae2458308fae1f0cb083870c8f3012eea58147f3b09d4a",
  
  /// This is already shown for normal accounts
  /// But on new node release. This is also shown when making a request with an ID of a Smart Contract
  "name": "ohager",
  "description": "{\"nm\":\"ohager\",\"ds\":\"Just a simple dev... or not?\",\"av\":{\"QmbbjnCFd8jELVZkVtokChaYAxFMjoGsuwhNeiPrgZGgo3\":\"image/png\"},\"bg\":{\"Qmd45gVYNvz5LPuNfrx8zDH571kz4h8vTRHdZhSFRZx3Hz\":\"image/jpeg\"},\"hp\":\"https://signum.network\",\"tw\":\"https://twitter.com/ohager5\",\"sc\":[]}",
  
  /// New properties...
  "isAT": false,
  "iSecured": true,
  /// End of new properties...
  
  /// Other remaining properties included by default...
}
```

### Describe the solution you'd like
The interface `Account` needs to be updated.
It must show the `isAT` and `isSecured` properties

### Additional context
The both flags shall simplify the inspection of accounts.

`isAT` = true, if a public key is 000..000
`isSecured` = false, if no public key was assigned. This shall raise awareness of insecure accounts.

**Signum Node Release Changelog:**
https://github.com/signum-network/signum-node/releases/tag/v3.8.0

**SignumJS Api Documentation**
`Account` interface link:
https://signum-network.github.io/signumjs/interfaces/core.account.html

**Comment by ohager** [comment]
done
