### ISSUE TITLE
Add new parameter on `GetAssetTradesArgs` interface

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signumjs#77]
**Is your feature request related to a problem? Please describe.**
The get token trades requests has a parameter which is not supported on SignumJS
The parameter is called `includeAssetInfo`

![image](https://github.com/signum-network/signumjs/assets/35440957/356a8c55-57ac-44d1-8a0c-61efab387a09)

As you can see on the SignumJS api documentation that parameter is missing
![image](https://github.com/signum-network/signumjs/assets/35440957/e074c2c2-7ddd-438b-b33e-bb52c940c0a5)
https://signum-network.github.io/signumjs/interfaces/core.getassettradesargs.html

**Describe the solution you'd like**
Add support for that parameter

**Additional Context**
According to the node API docs, the default value of that parameter is true

**Comment by ohager** [comment]
it was implicitely on `true, but added as optional param

**Comment by ohager** [comment]
done
